# Generated by Django 3.2.6 on 2021-08-19 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='apellido',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nombre',
            new_name='nombres',
        ),
    ]
